name = "LIBLINEAR"
uuid = "2d691ee1-e668-5016-a719-b2531b85e0f5"
authors = ["innerlee"]
repo = "https://github.com/innerlee/LIBLINEAR.jl.git"
version = "0.6.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
liblinear_jll = "275f1f90-abd2-5ca1-9ad8-abd4e3d66eb7"

[compat]
julia = "1.3"
liblinear_jll = "~2.47.0"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles"]
